import type { Metadata } from "next"
import { Cairo } from "next/font/google"

import "./globals.css"

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["700", "600", "500", "400", "300"],
})

export const metadata: Metadata = {
  title: "Wedentis",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={cairo.className}>{children}</body>
    </html>
  )
}
